- docs/sdk/client-side-sdks/react-native.md
- updated to include `react-native-get-random-values` library import that will make the code work when anonymous user ids are generated
> Update to React Native documentation

- docs/sdk/features/domain-proxy.md
Added some initial docs for domain proxying
> Adding domain proxying documentation

- docs/sdk/features/custom-domains.md
- docs/sdk/features/domain-proxy.md
> Change domain proxy name

- docs/home/feature-management/edgedb/edgedb.md
- docs/sdk/client-side-sdks/ios.md
- add edgedb section and example to ios sdk page
- add ios under client side sdks for edgedb page
> add iOS EdgeDB docs

- docs/home/feature-management/edgedb/edgedb.md
- docs/sdk/server-side-sdks/node.md
- add Edge DB example to Node.js docs
- add link to Node.js from Edge DB docs
> Update Node.js docs for Edge DB

- docs/tools-and-integrations/Bitbucket/bb-feature-usage-action.md
- docs/tools-and-integrations/Bitbucket/bb-pr-comment-insights.md
- docs/tools-and-integrations/Github/gh-feature-usage-action.md
- docs/tools-and-integrations/Github/gh-pr-comment-insights.md
- Added docs for pr insights
- Added the redirect to devcycle url's
> Adding Bitbucket Pr Comment Insights Documentation

- docs/sdk/sdk-types.md
- docs/sdk/server-side-sdks/dotnet-cloud.md
- docs/sdk/server-side-sdks/dotnet-local.md
- docs/sdk/server-side-sdks/java-cloud.md
- docs/sdk/server-side-sdks/java-local.md
- migrate existing Java SDK docs to Java Cloud Bucketing SDK
- introduce a new page for Java Local Bucketing SDK
> update docs for Java Bucketing

- docs/sdk/client-side-sdks/android.md
- docs/sdk/client-side-sdks/ios.md
- docs/sdk/features/realtime-updates.md
* add iOS and Android section to Realtime Updates feature page
* update the Variable Updates section to reference the Realtime updates page
> chore: add mobile realtime updates section to features

- docs/sdk/client-side-sdks/android.md
Add Java Example for using Variables values section and bump the Android SDK version to the latest (1.1.2)
> Add Java Example for Variables

- docs/sdk/client-side-sdks/android.md
Document existing Android initialization options (not including cache options)
> Add android initialization options

- docs/sdk/client-side-sdks/react.md
> add docs to explain React 17 resolution for build issues

- docs/sdk/client-side-sdks/javascript.md
> Remove trailing equal signs under table

- docs/sdk/client-side-sdks/flutter.md
- docs/sdk/features/all-features.md
- docs/sdk/features/all-variables.md
- docs/sdk/features/evaluating.md
- docs/sdk/features/identify.md
- docs/sdk/features/initialization.md
- docs/sdk/features/realtime-updates.md
- docs/sdk/features/reset.md
- docs/sdk/features/track.md
- docs/sdk/sdk-types.md
- docusaurus.config.js
> Flutter SDK Docs

- docs/sdk/client-side-sdks/javascript.md
added event tracking example to jssdk docs
> Jssdk docs updates

- docs/sdk/server-side-sdks/java-cloud.md
Update the Maven and Gradle to point to the latest version for the Java Cloud Bucketing SDK
> Update installation version on java-cloud.md

- docs/best-practices/serverless/serverless-cloud-functions.md
- docs/home/index.mdx
- sidebars.js
- src/pages/coming-soon.jsx
- src/pages/index.jsx
- fix typo for `Console`
- update links on home page to route correctly
> [fix] update links on landing page to point to the right routes

- docs/sdk/server-side-sdks/node.md
This seemed to have moved recently.
> Update link to DVCUser

- docs/sdk/client-side-sdks/flutter/_category_.yml
- docs/sdk/client-side-sdks/flutter/flutter-gettingstarted.md
- docs/sdk/client-side-sdks/flutter/flutter-install.md
- docs/sdk/client-side-sdks/flutter/flutter-usage.md
- docs/sdk/client-side-sdks/flutter/flutter.md
- docs/sdk/example-apps.md
- docs/sdk/features/all-features.md
- docs/sdk/features/all-variables.md
- docs/sdk/features/evaluating.md
- docs/sdk/features/identify.md
- docs/sdk/features/initialization.md
- docs/sdk/features/reset.md
- docs/sdk/features/track.md
- split into Installation, Getting Started, Usage
- add badges on each subpage
> split Flutter docs into three sections

- docs/best-practices/feature-grouping.md
Minor text updates for clarity.
> Minor Text Updates

- docs/home/feature-management/features-and-variables/targeting-users.md
Feel free to disregard if they don't make sense. 
However, the phrase below must be corrected do to an artifact error. 
"To understand the impact of turning a feature on or off in a Feature" 
to 
"To understand the impact of turning a feature on or off in a environment"
> Minor Text Changes

- docs/sdk/server-side-sdks/go/go-gettingstarted.md
- docs/sdk/server-side-sdks/go/go-usage.md
Updated page previews:
- [Getting Started](https://github.com/DevCycleHQ/devcycle-docs/blob/161c6f884851a73bdf684495aa6ce76dd3184e83/docs/sdk/server-side-sdks/go/go-gettingstarted.md)
- [Usage](https://github.com/DevCycleHQ/devcycle-docs/blob/161c6f884851a73bdf684495aa6ce76dd3184e83/docs/sdk/server-side-sdks/go/go-usage.md)
> Update go SDK examples to match current API

- docs/sdk/client-side-sdks/ios/ios-install.md
- docs/sdk/client-side-sdks/react-native/react-native-install.md
- docs/sdk/client-side-sdks/react/react-install.md
- docs/sdk/index.mdx
- docs/sdk/server-side-sdks/java-cloud/java-cloud-install.md
- docs/sdk/server-side-sdks/java-local/java-local-install.md
- docs/sdk/server-side-sdks/php/php-install.md
- docs/tools-and-integrations/index.mdx
- docusaurus.config.js
- package.json
- yarn.lock
This PR fixes issues with tabs not displaying in-app and resolves the issue with loss of heading titles for searchability.
> Fix Tab Display Issues

- docs/best-practices/feature-flag-cleanup.md
- docs/tools-and-integrations/cli.md
~Blocker: need to add a youtube link for the demo~
video is on youtube and linkedin the docs
> [chore] add cleanup command documentation in best practices

- docs/sdk/server-side-sdks/java-local/java-local-install.md
- yarn.lock
- clarify x86_64 JDK requirement
Preview:
> DVC-0000 [chore]: update Server Java Local installation requirements

- docs/sdk/server-side-sdks/go/go.md
> Fix Broken Link to Bucketing API in go.md

- package.json
- plugins/devcycle/index.js
- plugins/devcycle/theme/MDXComponents/Toggle.js
- src/theme/Layout/index.js
- yarn.lock
`Toggle` component can now use variable values from `allVariables()` from the jssdk on the server or `useVariableValue` from the react sdk on the client.
NEATO
> enables static rendering of the Toggle component

- docusaurus.config.js
> removes devcycle cdn script

- docs/sdk/client-side-sdks/react/react-gettingstarted.md
add docs for deferred mode for the React SDK
> deferred docs for react SDK

- docs/tools-and-integrations/index.mdx
- docs/tools-and-integrations/snowflake.md
Added a new page for Snowflake data sharing under Tools & Integrations
> Create Snowflake Integration Page

- docs/sdk/index.mdx
- docs/sdk/server-side-sdks/python/python-gettingstarted.md
- docs/sdk/server-side-sdks/python/python-install.md
- docs/sdk/server-side-sdks/python/python-usage.md
- docs/sdk/server-side-sdks/python/python.md
- updated code samples
- Added content for the Local Bucketing SDK
> Adding Python Local Bucketing SDK 

- package.json
- src/theme/Layout/index.js
- yarn.lock
https://vercel.com/docs/concepts/analytics/quickstart
> chore(analytics): adds vercel analytics

- docs/sdk/server-side-sdks/java-local/java-local-install.md
- fix bad Maven link from Android SDK to Java Server SDK for Java Local Bucketing
> DVC-0000 [fix]: update Java Local maven link to Java Server SDK

- src/css/custom.css
Resolves the issues with mid-size screen's and the primary navbar.
> Initial CSS Fix

- docs/introduction/core-concepts/feature-hierarchy.md
Attempt a more detailed explanation of our "feature hierarchy" and why it's a powerful concept.
> more detailed docs for feature hierarchy

- docs/examples.mdx
- docs/integrations/index.mdx
tvOS is always capitalized with lowercase `tv`
also fix typo for "interoperability"
> fix capitalization of tvos

- src/modules/analyticsModule.js
- src/modules/rudderstackClientModule.js
unnecessary event call that gets triggered on initial page load.
> removed track call on page load

- docs/community/calendar.mdx
- docusaurus.config.js
- src/css/custom.css
Add an Embed to the Public Google Calendar to the Docs.
> Add Community Calendar

- docs/extras/advanced-targeting/self-targeting.md
- docusaurus.config.js
- update self-targeting CLI docs to include overrides list command
> DVC-8692 [chore]: update Self Targeting CLI commands docs

- docusaurus.config.js
- package.json
- src/modules/analyticsModule.js
- yarn.lock
This reverts commit 8f4f08ca421f6f8e67a4706439cb48e1e648339d.
> Revert "Rudderstack implementation (#380)"

- docs/sdk/client-side-sdks/react/react-gettingstarted.md
- remove references to async provider
- clean up introduction language
- update examples to use a single code block
> update react examples and language

- docs/essentials/features.md
- docs/essentials/status-and-lifecycle.md
- yarn.lock
Note: Archive info removed. Kept some as coming soon. 
Other essentials pages do not have images. Kept simple and in line with the others.
> Complete feature

- README.md
- docs/integrations/openfeature.mdx
- docs/sdk/server-side-sdks/go/go-openfeature.md
- docs/sdk/server-side-sdks/java-cloud/java-cloud-openfeature.md
- docs/sdk/server-side-sdks/java-local/java-local-openfeature.md
- Added docs for using OpenFeature in both the local and cloud SDKs
- Fixed a few spelling mistakes
> feat: Java SDK OpenFeature docs

- docs/integrations/openfeature.mdx
- docs/sdk/server-side-sdks/dotnet/dotnet-openfeature.md
- docs/sdk/server-side-sdks/go/go-openfeature.md
- docs/sdk/server-side-sdks/node/node-openfeature.md
- docs/sdk/server-side-sdks/python/python-openfeature.md
[Quick Preview](https://github.com/DevCycleHQ/devcycle-docs/blob/DVC-9440/docs/sdk/server-side-sdks/python/python-openfeature.md)
> doc: Python OpenFeature docs (DVC-9440)

- docs/introduction/architecture.md
- updated Server SDK docs to note they do not yet support SSE
> chore: updated server sdk architecture docs to note that they do not support sse yet

- docs/extras/audit-log/audit-log.md
added note to docs on when this feature went live (no modifications tracked before December 2023)
> Audit Log - Release Date Added to Docs

- docs/sdk/client-side-sdks/react/react-gettingstarted.md
- add missing hook call to deferred mode docs that shows how to obtain the client
> add usage of hook to obtain devcycle client

- docs/integrations/index.mdx
> Update integrations blurb

- docs/extras/audit-log/audit-log.md
- docs/extras/webhooks/_category_.yml
- docs/extras/webhooks/webhooks.md
- docs/integrations/index.mdx
Webhooks Docs
-- Creating a Webhook
-- Example Payload
-- Testing a Webhook
-- Deleting a Webhook
> Cor 2290 - Webhooks Docs

- docs/examples.mdx
- docs/sdk/client-side-sdks/nextjs/nextjs-install.md
- docs/sdk/client-side-sdks/nextjs/nextjs-usage-app.md
- docs/sdk/client-side-sdks/nextjs/nextjs-usage-pages.md
- docs/sdk/client-side-sdks/nextjs/nextjs.md
- docs/sdk/index.mdx
- src/components/CustomDocCard/index.js
- src/components/CustomDocCard/styles.module.css
- fix section card things to wrap instead of truncate their contents and match height with each other
- rename NextJS to Next.js everywhere
- add docs for how to render in static mode
- change next example to point to next example
> add static mode docs for Nextjs

- docs/examples.mdx
- docs/sdk/server-side-sdks/java-local/java-local-usage.md
- docs/sdk/server-side-sdks/python/python-gettingstarted.md
- Update relevant apps to to new DevCycleHQ-Labs links
- Update Java apps (broken link)
- Small fixes to Java SDK docs
> Update example app links

- docusaurus.config.js
- src/theme/Footer/index.js
Changing the blog link from https://devcycle.com/blog to https://blog.devcycle.com
> Update Blog Link

- docs/examples.mdx
- docs/sdk/server-side-sdks/php/php-install.md
- Update PHP example app link
- Update PHP install instructions
> Update PHP example app link

- docs/sdk/client-side-sdks/react/react-openfeature.md
Adding docs for using React OpenFeature SDK with the existing JS Web Provider
> feat: adding docs for using React OpenFeature SDK

- docs/examples.mdx
Depends on the [example app PR](https://github.com/DevCycleHQ-Labs/example-ruby/pull/1) being merged
> Update ruby example app link

- docs/examples.mdx
- docs/sdk/server-side-sdks/dotnet/dotnet-gettingstarted.md
- docs/sdk/server-side-sdks/dotnet/dotnet-install.md
- Small updates to .NET SDK docs
- Update .NET local bucketing example link
Note: this should wait for the [example app PR](https://github.com/DevCycleHQ-Labs/example-dotnet/pull/1) to be merged
> Update .NET SDK docs

- docs/sdk/server-side-sdks/dotnet/dotnet-gettingstarted.md
Added SetLogger code to the example in the "To start" section
> Include Logger in Getting Started Section

- docs/sdk/client-side-sdks/ios/ios-gettingstarted.md
- docs/sdk/features.md
- update Custom Domain setup instructions for JS SDK initialization
> fix: update custom domain JS SDK initialization to use the correct key

- docs/sdk/server-side-sdks/nestjs/nestjs-usage.md
Update NestJS docs with added DevCycleService methods
> Add DevCycleService to Nest SDK docs

- docs/sdk/features.md
Add some explanation about initialization to that section of the SDK features
> explain initialization

- docs/essentials/keys.md
- add headers where necessary
- clean up and update guides on how to get to things on the dashboard
> cleanup keys

- docs/index.mdx
According to Brad this isn't a thing anymore
> remove office hours banner

- docs/sdk/client-side-sdks/javascript/javascript.md
- docs/sdk/client-side-sdks/nextjs/nextjs.md
- docs/sdk/client-side-sdks/react/react.md
Also a link to a github page about polyfilling fetch
> Add a note to js sdks that they rely on the fetch api

- docs/sdk/client-side-sdks/react-native/react-native-expo-install.md
- docs/sdk/client-side-sdks/react-native/react-native-gettingstarted.md
- docs/sdk/client-side-sdks/react-native/react-native-usage.md
- docs/sdk/client-side-sdks/react-native/react-native.md
- Updates React-Native SDK Docs
- Adds dedicated page for React-Native-Expo SDK Installation instructions
> chore: update React Native and Expo docs

- docs/sdk/sdk-proxy/index.md
- docs/sdk/sdk-proxy/installation.md
- docs/sdk/sdk-proxy/usage.md
Reword some stuff and remove some implementation details
> fix some of the sdk proxy docs

- yarn.lock
> chore: update ws and braces deps

- docs/extras/advanced-targeting/rollouts.md
July 17 --> Aug 14 - updated date for passthrough rollouts switchover
> Updated Date for Passthrough Rollouts Switchover

- docs/best-practices/migration.md
This PR separates out the steps for implementing the Multi-provider on the Server-side vs. Client Side.
> Separate Steps for Client-side vs. Server-side implementations

- docs/integrations/feature-importer.md
preview: https://devcycle-docs-du18ekg6h-devcyclehq.vercel.app/integrations/feature-importer#configuration
> chore: add ld api version note for feature importer

- docs/integrations/vercel-edge-config.md
A couple small changes given vercel feedback
> Update vercel-edge-config.md with vercel feedback

- package.json
- yarn.lock
> chore: update dependancies

- yarn.lock
> chore: update path-to-regexp dep

- vercel.json
This PR resolves the issues with trailing slashes not appropriately redirecting.
> Update Vercel Redirects to Address Trailing Slash

- yarn.lock
> chore: update http-proxy-middleware and cross-spawn

- docs/sdk/client-side-sdks/javascript/javascript-openfeature.md
- docs/sdk/client-side-sdks/react-native/react-native-expo-install.md
- docs/sdk/client-side-sdks/react-native/react-native-install.md
- docs/sdk/client-side-sdks/react-native/react-native-usage.md
- docs/sdk/client-side-sdks/roku/roku-gettingstarted.md
- docs/sdk/client-side-sdks/roku/roku-install.md
- docs/sdk/client-side-sdks/roku/roku-usage.md
- docs/sdk/server-side-sdks/node/node-openfeature.md
> feat: add OF tracking docs for Node + Web

- docs/sdk/client-side-sdks/react-native/react-native-expo-install.md
- docs/sdk/client-side-sdks/react-native/react-native-install.md
- docs/sdk/client-side-sdks/react-native/react-native.md
> feat: react native SSE docs

- docs/integrations/feature-importer.md
- docs/platform/extras/custom-domains.md
- docs/sdk/features.md
Changes:
- Change title on the Feature Importer page
- Update references to Custom Domain pricing requirements
> chore: Small Doc fixes

- docs/sdk/client-side-sdks/react/react-openfeature.md
> chore: cleanup react warning

- docs/index.mdx
- docs/integrations/openfeature.mdx
- docs/sdk/client-side-sdks/android/_category_.yml
- docs/sdk/client-side-sdks/angular/_category_.yml
- docs/sdk/client-side-sdks/angular/angular-example.mdx
- docs/sdk/client-side-sdks/angular/angular-gettingstarted.md
- docs/sdk/client-side-sdks/angular/angular-install.md
- docs/sdk/client-side-sdks/angular/angular-usage.md
- docs/sdk/client-side-sdks/angular/angular.md
- docs/sdk/client-side-sdks/flutter/_category_.yml
- docs/sdk/client-side-sdks/ios/_category_.yml
- docs/sdk/client-side-sdks/react-native/_category_.yml
- docs/sdk/client-side-sdks/roku/_category_.yml
- docs/sdk/index.mdx
- add docs for Angular OpenFeature SDK with DevCycle Provider
> feat: Angular install and getting started pages updated

- docs/sdk/client-side-sdks/angular/angular-gettingstarted.md
> chore: update angular install wizard position

- package.json
- yarn.lock
> chore: update undici dep

- yarn.lock
> chore: update babel / axios deps

- docs/essentials/overview.md
- docs/quickstart.md
Changes
- Add a what is Feature Flagging section to the overview page
- Link to the overview page from the getting started page
> Add section on what is feature flagging

- .devcycle/config.yml
> chore: configure devcycle project for vscode / cli

- docs/platform/feature-flags/status-and-lifecycle.md
- docs/platform/feature-flags/variables-and-variations/variables.md
- docs/sdk/features.md
Update the cleanup variables section of the Status and Lifecycle page and add it to the Variables page
> Update Variables and LifeCycles pages

- docs/cli-mcp/mcp-getting-started.md
- docs/cli-mcp/mcp-reference.md
> docs: add MCP install instructions for OpenAI Codex CLI + Gemini CLI
