DevCycleHQ/devcycle-docs

docs/sdk/client-side-sdks/react.md

- add example for new `useIsDVCInitialized` hook
- deprecate `asyncWithDVCProvider` with warning message

Update react.md for useIsDVCInitialized hook

---

docs/sdk/client-side-sdks/react-native.md

- add example for new `useIsDVCInitialized` hook
- deprecate `asyncWithDVCProvider` with warning message

Update react-native.md for useIsDVCInitialized

---

docs/sdk/client-side-sdks/android.md
docs/sdk/client-side-sdks/ios.md
docs/sdk/client-side-sdks/javascript.md
docs/sdk/client-side-sdks/react.md
docs/sdk/server-side-sdks/dotnet-cloud.md
docs/sdk/server-side-sdks/dotnet-local.md
docs/sdk/server-side-sdks/go.md
docs/sdk/server-side-sdks/java.md
docs/sdk/server-side-sdks/node.md
docs/sdk/server-side-sdks/php.md
docs/sdk/server-side-sdks/python.md
docs/sdk/server-side-sdks/ruby.md

Add badges with links to Package Manager (points to latest version) and to GH with Stars on Source Repo
JS based packages on NPM (including NodeJS Server SDK and JS, React and React-Native Client SDKs):
iOS:
Java & Kotlin based packages on Maven Central (Android Client SDK and Java Server SDK):
PHP:
Ruby:
Python:
C# / .NET:

Include Source links for SDK Docs

---

docs/sdk/client-side-sdks/javascript.md
docs/sdk/client-side-sdks/react-native.md
docs/sdk/client-side-sdks/react.md
docs/sdk/features/realtime-updates.md

- Clarified `onUpdate` usage and when it triggers
- Added section to JS SDK on what events can be subscribed to
- Added section in Features on Realtime Updates

chore: added feature section for realtime updates, clarified onUpdate

---

docs/sdk/server-side-sdks/node.md

reference links to `type.ts` seem to have been pointing to the wrong lines, fixed to link to the correct lines

fix node sdk type reference links

---

docs/sdk/client-side-sdks/android.md

Wait until the updated android SDK is released to merge this change

Add config caching options to DVCOptions builder

---

docs/sdk/server-side-sdks/java-local.md

Update the Maven and Gradle installation versions to point to the latest version for the Java Local Bucketing SDK

Update installation version on java-local.md

---

docs/sdk/client-side-sdks/android.md
docs/sdk/client-side-sdks/flutter.md
docs/sdk/client-side-sdks/ios.md
docs/sdk/client-side-sdks/javascript.md
docs/sdk/client-side-sdks/react-native.md
docs/sdk/client-side-sdks/react.md

- To Merge once iOS, Android and Flutter SDKs are published

DVC-6885 [fix]: update Client SDKs with disableRealtimeUpdates initialization option

---

docs/home/feature-management/edgedb/edge-flags.md
docs/sdk/example-apps.md
docs/sdk/features/all-features.md
docs/sdk/features/all-variables.md
docs/sdk/features/evaluating.md
docs/sdk/features/identify.md
docs/sdk/features/initialization.md
docs/sdk/features/track.md
docs/sdk/server-side-sdks/dotnet-cloud/_category_.yml
docs/sdk/server-side-sdks/dotnet-cloud/dotnet-cloud-gettingstarted.md
docs/sdk/server-side-sdks/dotnet-cloud/dotnet-cloud-install.md
docs/sdk/server-side-sdks/dotnet-cloud/dotnet-cloud-usage.md
docs/sdk/server-side-sdks/dotnet-cloud/dotnet-cloud.md

- include badges at top of every main and subpage
- split into Installation, Getting Started, Usage

split .NET Cloud SDK docs into three sections

---

docs/home/feature-management/edgedb/edge-flags.md
docs/sdk/example-apps.md
docs/sdk/features/all-features.md
docs/sdk/features/all-variables.md
docs/sdk/features/evaluating.md
docs/sdk/features/identify.md
docs/sdk/features/initialization.md
docs/sdk/features/track.md
docs/sdk/server-side-sdks/dotnet-cloud/dotnet-cloud-gettingstarted.md
docs/sdk/server-side-sdks/go/_category_.yml
docs/sdk/server-side-sdks/go/go-gettingstarted.md
docs/sdk/server-side-sdks/go/go-install.md
docs/sdk/server-side-sdks/go/go-usage.md
docs/sdk/server-side-sdks/go/go.md
docs/sdk/server-side-sdks/php/php-gettingstarted.md
docs/sdk/server-side-sdks/python/python-gettingstarted.md

- fix other urls in initialize to direct to gettingstarted instead of install page

[chore] split go sdk docs into individual pages

---

docs/sdk/client-side-sdks/android/android-usage.md

Update Android Realtime `onUpdate` docs to newer undeprecated method

chore: update realtime code

---

docs/home/feature-management/features-and-variables/variables-and-variations.md

Adding a note informing users that the only allowable Values for JSON variables are JSON objects with key-value pairs.

Allowable JSON Variable Values Update to variables-and-variations.md 

---

docs/sdk/client-side-sdks/javascript/javascript-typescript.md
docs/sdk/client-side-sdks/react/react-typescript.md
docs/tools-and-integrations/cli.md

Seems like markdown titles need to be (##) in order to be clickable in the sidebar

fix anchors on CLI page

---

.gitignore
README.md
docusaurus.config.js
package.json
src/css/custom.css
src/modules/devcycleClientModule.js
src/theme/Root.js
yarn.lock

Uses the jssdk to load kapa client side, based on env vars stored as secrets in vercel.
TODO:
- swap in and out intercom - it's currently part of gtm

adds devcycle sdk to docs

---

package.json
yarn.lock

Docusaurus plugin required react 18 since our sdks do (react 17 had a bug), but docusaurus doesn't officially support 18 until version 3. So an update to the plugin allows it to work with react 17, meaning this will be easier for users to install without having to bump react to 18 and seeing dev warnings.

back to react 17 with new plugin update

---

docs/sdk/server-side-sdks/dotnet-cloud/dotnet-cloud-gettingstarted.md
docs/sdk/server-side-sdks/dotnet-cloud/dotnet-cloud-usage.md
docs/sdk/server-side-sdks/dotnet-local/dotnet-local-gettingstarted.md
docs/sdk/server-side-sdks/dotnet-local/dotnet-local-usage.md
docs/sdk/server-side-sdks/go/go-usage.md
docs/sdk/server-side-sdks/java-cloud/java-cloud-gettingstarted.md
docs/sdk/server-side-sdks/java-cloud/java-cloud-usage.md
docs/sdk/server-side-sdks/java-local/java-local-gettingstarted.md
docs/sdk/server-side-sdks/java-local/java-local-usage.md
docs/sdk/server-side-sdks/python/python-usage.md
docs/sdk/server-side-sdks/ruby/ruby-usage.md

added entries and code samples for all the server SDKs that currently support setting custom client data
updated the Java and DotNet usage examples so they are code snippets instead of big boiler plate code samples

adding references to setClientCustomData

---

docs/sdk/client-side-sdks/android/android-usage.md

The current android code snippets result in type errors when used. Update `Variable<Any>` and `Variable<Object>` to use `BaseConfigVariable` instead

fix: Update android examples to use BaseConfigVariable

---

docs/sdk/client-side-sdks/react-native/react-native.md

- move expo incompatibility to caution banner at the top of React Native docs

chore: move expo compatibility to caution banner

---

docs/sdk/client-side-sdks/react/react-gettingstarted.md

Updated React SDK docs with the Start Options to disable automatic and custom event tracking.

Add disableEventTracking Options to React Docs

---

docs/examples.mdx

- just say Javascript as the name of the javascript example app

remove references to web elements from js example label

---

docs/integrations/gitlab/_category_.yml
docs/integrations/index.mdx
docusaurus.config.js

Add docs for GitLab code usages, sourced from the repo readme.
Note: this shouldn't be merged until the feature is ready for release

feat: Add gitlab code usage docs

---

docs/integrations/index.mdx
docusaurus.config.js

Add docs for GitLab merge request insights.
**Note: this shouldn't be merged until the feature is ready for release**

chore: add GitLab merge request insights docs

---

docs/sdk/client-side-sdks/react-native/react-native-gettingstarted.md
docs/sdk/client-side-sdks/react-native/react-native-install.md
docs/sdk/client-side-sdks/react-native/react-native-usage.md
docs/sdk/client-side-sdks/react-native/react-native.md

- link to React Native Expo Client SDK badge on npm
- add install step for SDK
- update caution banner to be an info banner that says React Native Expo is supported

chore: add docs support for React Native Expo SDK

---

package.json
yarn.lock

So this temporarily fixes this issue of compression on mobile views identified by @leslie-lau (see below).
This issue only occurs during build, as during dev it looks like this when loading:
This fix (reverting the redocusaurus to 1.6.0) is [a temporary fix for the moment based on the this issue](https://github.com/rohit-gohri/redocusaurus/issues/287)
Below is what it now looks like during loading on v1.6.0:

Attempt to Fix API Mobile View

---

docs/sdk/server-side-sdks/java-cloud/java-cloud-install.md
docs/sdk/server-side-sdks/java-local/java-local-install.md

We bumped the min java version to 11 and Gradle to 7.6. The sdk also supports WASM for both MacOS architectures

chore: updating the Java SDK requirements to match GitHub readme

---

docs/sdk/client-side-sdks/react-native/react-native-install.md

`withDVCProvider` isn't exported from the Expo SDK, so we should update the react native docs to just use `withDevCycleProvider`

Update react native to use withDevCycleProvider

---

docs/sdk/server-side-sdks/dotnet/dotnet-install.md

Make the dotnet table disappear. 
It messes up the docs embedding on the dashboard.

Remove the table for DotNet

---

docs/examples.mdx

swaps out the new links and adds a separate card for the regular react example vs the nextjs example

Swap out links to polished example apps for js, react, vue, node

---

docs/extras/advanced-variables/variable-defaults.md
docs/sdk/client-side-sdks/android/android-usage.md
docs/sdk/client-side-sdks/flutter/flutter-usage.md
docs/sdk/client-side-sdks/ios/ios-usage.md
docs/sdk/client-side-sdks/javascript/javascript-usage.md
docs/sdk/client-side-sdks/react-native/react-native-usage.md
docs/sdk/client-side-sdks/react/react-usage.md
docs/sdk/features.md
docs/sdk/server-side-sdks/dotnet/dotnet-usage.md
docs/sdk/server-side-sdks/go/go-usage.md
docs/sdk/server-side-sdks/java-cloud/java-cloud-usage.md
docs/sdk/server-side-sdks/java-local/java-local-usage.md
docs/sdk/server-side-sdks/node/node-usage.md
docs/sdk/server-side-sdks/php/php-usage.md
docs/sdk/server-side-sdks/python/python-usage.md
docs/sdk/server-side-sdks/ruby/ruby-usage.md

- add doc explaining variable defaulting behaviour
- add warning to allVariables method in various places
- fix missing content and structure of main "SDK features" landing page
- re-order sections of SDK Features to mention how to get a variable value first, and finish that section as well as add additional details about variable defaulting

docs updates for defaulting and allVariables

---

package.json
yarn.lock

- chore: update follow-redirects to 1.15.6
- chore: update docusaurus-plugin-remote-content to 4.0.0 and all deps that use axios to use axios ^1.6.0

Update out of date Dependencies

---

docusaurus.config.js

It's kind of unintuitive that the only way to return to "home" is by knowing you can click the logo

add home link to navbar

---

docs/extras/custom-domains/_category_.yml
docs/extras/custom-domains/custom-domains.md
docs/sdk/features.md
docs/sdk/index.mdx

- remove explanations of local vs cloud bucketing from main SDK page and move to SDK Features
- remove explanation of SDK Proxy
- create new page for custom domains
- remove explanation of custom domains from SDK Features
- move and write up explanation of resetting user in SDK features
- restructure Identification section in SDK Features
- remove redundant wording in various places
- remove "Local" and "Cloud" bucketing description labels from SDK tiles on SDKs page

clean up sdk section

---

docs/sdk/client-side-sdks/react/react-install.md

- Remove Create react App workaround because it is no longer necessary
- move React 17 warning to the end of the installation so its not the first thing you see

remove create react app instructions and move react 17 warning

---

docs/integrations/slack.md
docs/sdk/client-side-sdks/android/android-gettingstarted.md
docs/sdk/client-side-sdks/flutter/flutter-gettingstarted.md
docs/sdk/client-side-sdks/ios/ios-gettingstarted.md

- updates DevCycle Options to include API Proxy and Events API Proxy for Android, iOS and Flutter SDKs

fix: adds Events API Proxy Option for iOS and Android SDKs

---

docs/sdk/client-side-sdks/android/android-install.md
docs/sdk/client-side-sdks/flutter/flutter-install.md

- updates minimum Android API Version to 23 (was 21 on Android SDK and 26 on Flutter SDK)
- updates Flutter SDK install version to `^1.8.0`

fix: update minimum Android API Version to 23 instead of 21

---

docs/introduction/quickstart.md

- refactor `Feature Flags` to `feature flags`
- fix spelling mistakes
- reword a couple of awkward sentences

chore: fix typos and spelling mistakes in quickstart

---

bucketing-api.yaml

Not actually versioned - and this adds confusion

Remove version from bucketing api docs

---

docs/sdk/client-side-sdks/nextjs/nextjs-usage-app.md
docs/sdk/client-side-sdks/nextjs/nextjs-usage-pages.md

Update Nextjs docs to reflect updates to initialization that now require both the server and client SDK keys

update nextjs docs for new initialization signature

---

docs/extras/advanced-targeting/rollouts.md

Remove PHP SDK from Require SDK Update List for Passthrough

Remove PHP SDK from Require SDK Update List for Passthrough

---

docs/best-practices/engineering-led-experiments.md
docs/best-practices/feature-grouping.md
docs/best-practices/product-led-experimentation.md
docs/essentials/feature-experimentation.md
docs/extras/metrics/creating-and-managing-metrics.md
docs/extras/web-debugger.mdx

- moved Feature Experimentation docs page under Essentials section
- added a clarification on what properties can be updated via debugger

Updating Location of Experimentation Docs + small Debugger Edit

---

docs/sdk/client-side-sdks/ios/ios-install.md

- added note for alias of package for SPM

chore: added note for package url conflicts

---

docs/sdk/features.md
docs/sdk/server-side-sdks/dotnet/dotnet-gettingstarted.md
docs/sdk/server-side-sdks/dotnet/dotnet-usage.md
docs/sdk/server-side-sdks/go/go-gettingstarted.md
docs/sdk/server-side-sdks/go/go-usage.md
docs/sdk/server-side-sdks/java/java-gettingstarted.md
docs/sdk/server-side-sdks/java/java-usage.md
docs/sdk/server-side-sdks/nestjs/nestjs-gettingstarted.md
docs/sdk/server-side-sdks/nestjs/nestjs-usage.md
docs/sdk/server-side-sdks/node/node-gettingstarted.md
docs/sdk/server-side-sdks/node/node-usage.md
docs/sdk/server-side-sdks/python/python-gettingstarted.md
docs/sdk/server-side-sdks/python/python-usage.md
docs/sdk/server-side-sdks/ruby/ruby-gettingstarted.md
docs/sdk/server-side-sdks/ruby/ruby-usage.md

Update realtime update docs now that SDKs default to it enabled

feat: update realtime update docs

---

docs/essentials/architecture.md

chore: cleanup SSE refrences on architecture page

---

docs/sdk/client-side-sdks/react/react-openfeature.md

- update OF react docs to use `@devcycle/openfeature-react-provider` and `DevCycleReactProvider`

feat: update OF react docs to use @devcycle/openfeature-react-provider

---

docs/essentials/key-features.md
docs/essentials/overview.md

Overview page now points to Key Features instead of itself

Fix pagination on overview page

---

docs/integrations/openfeature.mdx
docs/sdk/server-side-sdks/ruby/ruby-example.mdx

Contains the following changes:
- Add the Ruby OpenFeature example app to the example apps section
- Add the Ruby OpenFeature SDK to the list of SDKs on the OpenFeature page

Add Ruby Example App to docs

---

.github/workflows/action.yml

Potential fix for [https://github.com/DevCycleHQ/devcycle-docs/security/code-scanning/2](https://github.com/DevCycleHQ/devcycle-docs/security/code-scanning/2)
To fix the issue, we will add a `permissions` block at the root level of the workflow file. This block will specify `contents: read`, which is the minimum required permission for the workflow to read the repository contents and check Markdown links. This change ensures that the workflow does not have unnecessary write permissions.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore: Potential fix for code scanning alert no. 2: Workflow does not contain permissions

---

.github/workflows/broken-link-check.yml

Potential fix for [https://github.com/DevCycleHQ/devcycle-docs/security/code-scanning/1](https://github.com/DevCycleHQ/devcycle-docs/security/code-scanning/1)
To fix the issue, we need to add a `permissions` block to the workflow. Since the workflow is performing a broken link check, it likely only requires `contents: read` permissions. This block should be added at the root level of the workflow to apply to all jobs, as there is only one job in this workflow.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore: Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

docs/integrations/openfeature.mdx
docs/sdk/client-side-sdks/ios/ios-openfeature.md
docs/sdk/client-side-sdks/javascript/javascript-openfeature.md

docs: add iOS OpenFeature Provider docs

---

docs/sdk/server-side-sdks/dotnet/dotnet-usage.md
docs/sdk/server-side-sdks/go/go-usage.md
docs/sdk/server-side-sdks/java/java-usage.md
docs/sdk/server-side-sdks/node/node-usage.md
docs/sdk/server-side-sdks/php/php-usage.md
docs/sdk/server-side-sdks/python/python-usage.md
docs/sdk/server-side-sdks/ruby/ruby-usage.md

- added docs for evaluation hooks

chore: update docs with variable evaluation usage

---

package.json
yarn.lock

This PR removes unused dependencies while ensuring the documentation site remains fully functional.
- **Vercel CLI and related packages** - `vercel`, `@vercel/*`, `@edge-runtime/*`
- **FontAwesome icons** - `@fortawesome/*` packages 
- **Build tools** - `webpack`, `esbuild@0.14.47`, `ts-node`, `ts-morph`
- **Analytics** - `mixpanel-browser`, `rrweb`
- **Miscellaneous** - Various unused utilities and dependencies
Removed unused resolutions, kept essential `send@0.18.0` resolution.
- ✅ `yarn dev` works
- ✅ `yarn build` succeeds
- ✅ Documentation site functional
- ✅ API docs render correctly
Significantly reduces dependency footprint while maintaining all functionality.

Chore: prune unused dependencies and resolutions

---

docs/sdk/server-side-sdks/dotnet/dotnet-usage.md
docs/sdk/server-side-sdks/go/go-usage.md
docs/sdk/server-side-sdks/java/java-usage.md
docs/sdk/server-side-sdks/node/node-usage.md
docs/sdk/server-side-sdks/php/php-usage.md
docs/sdk/server-side-sdks/python/python-usage.md
docs/sdk/server-side-sdks/ruby/ruby-usage.md

This field provides evaluation details such as reason, details, and targetId for variable bucketing (see [Evaluation Reasons](/sdk/features#evaluation-reasons)).

Update SDK documentation to include 'eval' field in Variable object

---

src/css/custom.css

fix: darkmode on more diagrams

---

_redirects

- fix the redirects from indexed pages

fix debug tools and webdebugger redirects
